name: django
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.7.15
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - ncurses=6.5
  - openssl=3.0.17
  - pip=25.1
  - pthread-stubs=0.3
  - python=3.10.18
  - readline=8.3
  - sqlite=3.50.2
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - absl-py==2.3.1
      - accelerate==1.9.0
      - aiodns==3.5.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiomultiprocess==0.9.1
      - aioresponses==0.7.8
      - aiosignal==1.4.0
      - aiosqlite==0.21.0
      - alembic==1.16.4
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - altgraph==0.17.4
      - amqp==5.3.1
      - annotated-types==0.7.0
      - anyio==4.9.0
      - argcomplete==3.6.2
      - arrow==1.3.0
      - asgiref==3.9.1
      - async-timeout==5.0.1
      - attrs==25.3.0
      - backoff==2.2.1
      - backports-asyncio-runner==1.2.0
      - bcrypt==4.3.0
      - beautifulsoup4==4.13.4
      - billiard==4.2.1
      - bitsandbytes==0.46.1
      - black==25.1.0
      - blinker==1.9.0
      - bottle==0.12.25
      - cachelib==0.13.0
      - celery==5.5.3
      - censys==2.2.17
      - certifi==2025.7.14
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.2.1
      - click-didyoumean==0.3.1
      - click-plugins==1.1.1.2
      - click-repl==0.3.0
      - colorama==0.4.6
      - content-security-policy==0.2.3
      - contourpy==1.3.2
      - crcmod==1.7
      - cron-descriptor==2.0.6
      - cryptography==42.0.8
      - cssselect==1.3.0
      - curl-cffi==0.13.0
      - cycler==0.12.1
      - datarecorder==3.6.2
      - datasets==4.0.0
      - deprecated==1.2.18
      - dill==0.3.8
      - django==5.2.4
      - django-celery-beat==2.8.1
      - django-cors-headers==4.7.0
      - django-extensions==4.1
      - django-ninja==1.4.5
      - django-rich==2.2.0
      - django-simple-history==3.11.0
      - django-timezone-field==7.2.1
      - djangorestframework==3.16.0
      - dnslib==0.9.26
      - dnspython==2.7.0
      - downloadkit==2.0.7
      - drissionpage==4.1.1.2
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - eventlet==0.40.2
      - exceptiongroup==1.3.0
      - fastapi==0.116.1
      - filelock==3.18.0
      - flake8==7.3.0
      - flask==3.0.2
      - flask-cors==4.0.0
      - flask-jwt-extended==4.7.1
      - flask-login==0.6.3
      - flask-migrate==4.0.5
      - flask-session==0.7.0
      - flask-sqlalchemy==3.1.1
      - flask-wtf==1.1.1
      - fonttools==4.59.0
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - ftfy==6.3.1
      - func-timeout==4.3.5
      - gevent==25.5.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gql==4.0.0
      - graphql-core==3.2.7
      - graphviz==0.21
      - greenlet==3.2.3
      - grpcio==1.73.1
      - gunicorn==23.0.0
      - h11==0.16.0
      - h2==4.3.0
      - hacker-gf==0.1.0
      - hf-xet==1.1.5
      - hpack==4.1.0
      - httpcore==1.0.9
      - httpretty==1.1.4
      - httptools==0.7.1
      - httpx==0.28.1
      - huggingface-hub==0.33.4
      - hyperframe==6.1.0
      - identywaf==1.0.127
      - idna==3.10
      - impacket==0.12.0
      - iniconfig==2.1.0
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jmespath==0.10.0
      - joblib==1.5.1
      - jsonlines==4.0.0
      - kiwisolver==1.4.8
      - kombu==5.5.4
      - ldap3==2.9.1
      - ldapdomaindump==0.10.0
      - limits==5.4.0
      - loguru==0.7.3
      - lxml==6.0.0
      - mako==1.3.10
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgspec==0.19.0
      - multidict==6.6.3
      - multiprocess==0.70.16
      - multiprocessing-logging==0.3.4
      - mypy==1.17.0
      - mypy-extensions==1.1.0
      - netaddr==1.3.0
      - networkx==3.4.2
      - numpy==2.2.0
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - openpyxl==3.1.5
      - orjson==3.11.0
      - oss2==2.19.1
      - outcome==1.3.0.post0
      - packaging==25.0
      - pandas==2.3.1
      - paramiko==3.5.1
      - parsel==1.10.0
      - pathspec==0.12.1
      - peft==0.16.0
      - pillow==11.3.0
      - platformdirs==4.3.8
      - playwright==1.54.0
      - pluggy==1.6.0
      - pluginbase==1.0.1
      - prometheus-client==0.17.1
      - prompt-toolkit==3.0.51
      - propcache==0.3.2
      - protobuf==6.31.1
      - psutil==7.0.0
      - psycopg2-binary==2.9.10
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycares==4.9.0
      - pycodestyle==2.14.0
      - pycparser==2.22
      - pycryptodome==3.23.0
      - pycryptodomex==3.23.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydotplus==2.0.2
      - pyee==13.0.0
      - pyflakes==3.4.0
      - pygments==2.19.2
      - pyinstaller==6.14.2
      - pyinstaller-hooks-contrib==2025.7
      - pyjwt==2.10.1
      - pymongo==4.14.1
      - pymysql==1.1.1
      - pynacl==1.5.0
      - pyopenssl==24.0.0
      - pyparsing==3.2.3
      - pysocks==1.7.1
      - pytest==8.4.1
      - pytest-asyncio==1.1.0
      - python-crontab==3.3.0
      - python-dateutil==2.9.0.post0
      - python-magic==0.4.27
      - python-nmap==0.7.1
      - python-wappalyzer==0.3.1
      - pytz==2025.2
      - pyyaml==6.0.2
      - rarfile==4.2
      - redis==5.2.1
      - regex==2024.11.6
      - requests==2.32.4
      - requests-file==2.1.0
      - requests-toolbelt==1.0.0
      - retrying==1.4.1
      - rich==14.0.0
      - ruff==0.12.4
      - safetensors==0.5.3
      - scapy==2.6.1
      - scikit-learn==1.7.1
      - scipy==1.15.3
      - selenium==4.15.2
      - sentencepiece==0.2.0
      - sentry-sdk==2.33.2
      - setuptools==80.9.0
      - shcheck==1.6.7
      - shodan==1.31.0
      - simpleeval==1.0.3
      - six==1.17.0
      - slowapi==0.1.9
      - smmap==5.0.2
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.7
      - sqlalchemy==2.0.41
      - sqlparse==0.5.3
      - starlette==0.47.2
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - tldextract==5.3.0
      - tokenizers==0.21.2
      - tomli==2.2.1
      - torch==2.7.1
      - tqdm==4.67.1
      - transformers==4.53.3
      - trio-websocket==0.12.2
      - triton==3.3.1
      - types-python-dateutil==2.9.0.20250809
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - ujson==5.10.0
      - urllib3==1.26.20
      - uvicorn==0.35.0
      - uvloop==0.21.0
      - vine==5.1.0
      - w3lib==2.3.1
      - wafw00f==2.3.2
      - waitress==3.0.1
      - wandb==0.21.0
      - wcwidth==0.2.13
      - websocket-client==1.8.0
      - websockets==11.0.3
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - wsproto==1.2.0
      - wtforms==3.2.1
      - xlsxwriter==3.2.5
      - xvfbwrapper==0.2.9
      - xxhash==3.5.0
      - yarl==1.20.1
      - zope-event==5.1.1
      - zope-interface==7.2
